### ISSUE TITLE
[REQUEST] Auto-repairing items if the npc offers repairs

### ISSUE THREAD

**Issue by cnolimes** [shirsig/SortBags#1]
I'm loving this addon and particularly the vendoring trash feature you've implemented. Was wondering if it's possible to create auto-repair feature too?

Regards

**Comment by shirsig** [comment]
Hey. I'm glad you like it.

I'm pretty swamped at the moment and I already have some other stuff in my backlog, even for this addon (someone requested that certain items like enchanting mats are grouped together rather than by rarity over all trade goods and I'm also working on a very experimental feature for sorting without actually moving, which is very hard to achieve without restricting yourself to a specific bag addon)

But in a week or two I should be able to do this.

**Comment by shirsig** [comment]
I've now had some time to work on clean up again but after thinking about it I'm not sure about this feature. What did you mean by auto-repair exactly? Because vendoring trash isn't really automatic. You still have to click the brush button. Of course that's much more convenient than manually finding all grays, but for repairing there's already a "repair all" button so it wouldn't make much of a difference. If you meant fully automatic repairing upon visiting a vendor then that might also be very annoying at times (e.g., when you're nearly broke). Plus, while it would be trivial to implement, I don't really see why it should be part of this addon. Vendoring is already a bit of a stretch but it does kind of make sense as part of "cleaning up" the inventory. Now, I wouldn't mind making a separate addon for this (would be literally like 10 lines of code or something) but I would be surprised if there isn't already an addon for automatic repairing?
edit: yes there is: http://www.vanilla-addons.com/dls/autorepair/ (and I think lazypig does it too)
